# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    flake8 src test
  displayName: 'Run Lint Tests'

- script: |
    python -m pip install pytest-azurepipelines
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html
  displayName: 'Run unit tests'

- script: |
    python -m pip install wheel
    python -m pip install pygments
    python setup.py sdist bdist_wheel
  displayName: 'Preparing for release'

- task: PyPIPublisher@0
  inputs:
    pypiConnection: 'Test PyPi'
    packageDirectory: 'src'
